# Generated by Django 2.2.1 on 2019-05-21 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=30)),
                ('project', models.CharField(max_length=30)),
                ('bulk_type', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('run_number', models.CharField(max_length=30)),
                ('wafer_number', models.CharField(max_length=30)),
                ('trec_id', models.CharField(max_length=30)),
                ('area', models.FloatField(blank=True)),
                ('thickness', models.FloatField(blank=True)),
                ('support_wafer_thickness', models.FloatField(blank=True)),
                ('resistivity', models.FloatField(blank=True)),
                ('dead_or_alive', models.CharField(choices=[('D', 'Dead'), ('A', 'Alive')], max_length=1)),
                ('ssd_responsible', models.CharField(max_length=30)),
                ('arrival_date', models.DateField(default=datetime.date.today)),
                ('current_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LocationTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('source_location', models.CharField(max_length=30, verbose_name='From')),
                ('destination_location', models.CharField(max_length=30, verbose_name='To')),
                ('internal_or_external', models.CharField(choices=[('External', 'External'), ('Internal', 'Internal')], max_length=10)),
                ('responsible_party', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=30)),
                ('detector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detectors.Detector')),
            ],
        ),
        migrations.CreateModel(
            name='Irradiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('irradiation_particle', models.CharField(max_length=30)),
                ('fluence_or_dose', models.DecimalField(decimal_places=10, max_digits=20)),
                ('energy_magnitude', models.FloatField()),
                ('energy_unit', models.CharField(max_length=10)),
                ('irradiation_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('detector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detectors.Detector')),
            ],
        ),
        migrations.CreateModel(
            name='Annealing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annealing_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('temperature', models.FloatField()),
                ('time', models.FloatField()),
                ('detector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detectors.Detector')),
            ],
        ),
    ]
