# Generated by Django 2.2.1 on 2019-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtransfer',
            name='description',
        ),
        migrations.AddField(
            model_name='detector',
            name='comment',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='comment',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='detector',
            name='bulk_type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='current_location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detector',
            name='producer',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='project',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='run_number',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='ssd_responsible',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='trec_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='type',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='detector',
            name='wafer_number',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='irradiation_particle',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='destination_location',
            field=models.CharField(max_length=256, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='source_location',
            field=models.CharField(max_length=256, verbose_name='From'),
        ),
    ]
