# Generated by Django 2.2.1 on 2019-05-22 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0002_auto_20190521_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annealing',
            name='annealing_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='annealing',
            name='temperature',
            field=models.FloatField(verbose_name='Temp in Celcius'),
        ),
        migrations.AlterField(
            model_name='annealing',
            name='time',
            field=models.FloatField(verbose_name='Time in minutes'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='area',
            field=models.FloatField(blank=True, verbose_name='Area (in cm sq)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Detector name or ID'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='resistivity',
            field=models.FloatField(blank=True, verbose_name='Resistivity (in ohm-cm)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='ssd_responsible',
            field=models.CharField(max_length=256, verbose_name='Person responsible for the detector'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='support_wafer_thickness',
            field=models.FloatField(blank=True, verbose_name='Support wafer thickness (in micrometer)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='thickness',
            field=models.FloatField(blank=True, verbose_name='Thickness (in micrometer)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='trec_id',
            field=models.CharField(max_length=256, verbose_name='TREC ID'),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='energy_magnitude',
            field=models.FloatField(verbose_name='Energy'),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='energy_unit',
            field=models.CharField(max_length=10, verbose_name='Unit of energy'),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='irradiation_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date and time'),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='irradiation_particle',
            field=models.CharField(max_length=256, verbose_name='Particle used for radiation'),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=256, verbose_name='Person undertaking the transfer'),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='transfer_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date and time'),
        ),
    ]
