# Generated by Django 2.2.1 on 2019-05-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0003_auto_20190522_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annealing',
            name='temperature',
            field=models.FloatField(verbose_name='Temp (in Celcius)'),
        ),
        migrations.AlterField(
            model_name='annealing',
            name='time',
            field=models.FloatField(verbose_name='Time (in minutes)'),
        ),
    ]
