# Generated by Django 2.2.1 on 2019-05-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0004_auto_20190522_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationtransfer',
            name='source_location',
        ),
    ]
