# Generated by Django 2.2.1 on 2019-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0005_remove_locationtransfer_source_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Area (in cm sq)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='resistivity',
            field=models.FloatField(blank=True, null=True, verbose_name='Resistivity (in ohm-cm)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='support_wafer_thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Support wafer thickness (in micrometer)'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='thickness',
            field=models.FloatField(blank=True, null=True, verbose_name='Thickness (in micrometer)'),
        ),
    ]
