# Generated by Django 2.2.1 on 2019-05-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0007_locationtransfer_source_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtransfer',
            name='source_location',
            field=models.CharField(editable=False, max_length=256, verbose_name='From'),
        ),
    ]
