# Generated by Django 2.2.1 on 2019-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0008_auto_20190525_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='trec_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='TREC ID'),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='source_location',
            field=models.CharField(default='The current location of this detector (auto-fill)', editable=False, max_length=256, verbose_name='From'),
        ),
    ]
