# Generated by Django 2.2.1 on 2019-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0009_auto_20190527_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradiation',
            name='hardness_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detector',
            name='type',
            field=models.CharField(max_length=256, verbose_name='Sensor type'),
        ),
    ]
