# Generated by Django 2.2.1 on 2019-05-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0010_auto_20190527_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annealing',
            options={'ordering': ['-annealing_datetime']},
        ),
        migrations.AlterModelOptions(
            name='detector',
            options={'ordering': ['-arrival_date']},
        ),
        migrations.AlterModelOptions(
            name='irradiation',
            options={'ordering': ['-irradiation_datetime']},
        ),
        migrations.AlterModelOptions(
            name='locationtransfer',
            options={'ordering': ['-transfer_datetime']},
        ),
    ]
