# Generated by Django 2.2.1 on 2019-05-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0011_auto_20190528_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='dead_or_alive',
            field=models.CharField(choices=[('D', 'Dead'), ('A', 'Alive')], max_length=1, verbose_name='Dead/Alive'),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='fluence_or_dose',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Fluence/Dose'),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='internal_or_external',
            field=models.CharField(choices=[('External', 'External'), ('Internal', 'Internal')], max_length=10, verbose_name='Internal/External'),
        ),
    ]
