# Generated by Django 2.2.1 on 2019-05-31 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0012_auto_20190531_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annealing',
            options={'ordering': ['-annealing_date']},
        ),
        migrations.AlterModelOptions(
            name='irradiation',
            options={'ordering': ['-irradiation_date']},
        ),
        migrations.AlterModelOptions(
            name='locationtransfer',
            options={'ordering': ['-transfer_date']},
        ),
        migrations.RemoveField(
            model_name='annealing',
            name='annealing_datetime',
        ),
        migrations.RemoveField(
            model_name='irradiation',
            name='irradiation_datetime',
        ),
        migrations.RemoveField(
            model_name='locationtransfer',
            name='transfer_datetime',
        ),
        migrations.AddField(
            model_name='annealing',
            name='annealing_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='irradiation',
            name='irradiation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='locationtransfer',
            name='transfer_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
