# Generated by Django 2.2.1 on 2019-05-31 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0013_auto_20190531_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annealing',
            name='annealing_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
