# Generated by Django 2.2.1 on 2019-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0014_auto_20190531_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradiation',
            name='fluence_or_dose',
            field=models.DecimalField(decimal_places=50, max_digits=100, verbose_name='Fluence/Dose'),
        ),
    ]
