# Generated by Django 2.2.2 on 2019-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0017_auto_20190531_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='run_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='irradiation_particle',
            field=models.CharField(max_length=256, verbose_name='Particle used for irradiation'),
        ),
    ]
