# Generated by Django 2.2.1 on 2019-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0018_auto_20190604_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradiation',
            name='fd_unit',
            field=models.CharField(default='neq/cm2', max_length=10, verbose_name='Unit of fluence/dose'),
            preserve_default=False,
        ),
    ]
