# Generated by Django 2.2.2 on 2019-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0019_irradiation_fd_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='energy_magnitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy'),
        ),
        migrations.AlterField(
            model_name='irradiation',
            name='energy_unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unit of energy'),
        ),
        migrations.AlterField(
            model_name='locationtransfer',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Person undertaking the transfer'),
        ),
    ]
