# Generated by Django 2.2.2 on 2019-06-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0020_auto_20190605_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='dead_or_alive',
            field=models.CharField(choices=[('Dead', 'Dead'), ('Alive', 'Alive'), ('Unknown', 'Unknown')], max_length=10, verbose_name='Dead/Alive'),
        ),
    ]
