# Generated by Django 2.2.2 on 2019-06-27 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectors', '0022_auto_20190627_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_detector_id', message='Detector ID cannot have special characters', regex='^[\\w-]+$')], verbose_name='Detector name or ID'),
        ),
    ]
